import type { User } from '../types';

export const seedUsers: User[] = [
  // Admins
  {
    id: 'user-admin-1',
    org_id: 'org-1',
    email: 'Shubham.negi@pw.live',
    full_name: 'Shubham Negi',
    avatar_url: null,
    role: 'admin',
    department: 'Administration',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-admin-2',
    org_id: 'org-1',
    email: 'Saksham.agarwal@pw.live',
    full_name: 'Saksham Agarwal',
    avatar_url: null,
    role: 'admin',
    department: 'Administration',
    created_at: '2026-03-01T00:00:00Z',
  },

  // Members
  {
    id: 'user-3',
    org_id: 'org-1',
    email: '',
    full_name: 'Ayush Satyam',
    avatar_url: null,
    role: 'member',
    department: 'Finance Operations',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-4',
    org_id: 'org-1',
    email: '',
    full_name: 'Aditya Nath Tiwari',
    avatar_url: null,
    role: 'member',
    department: 'Business Operations',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-5',
    org_id: 'org-1',
    email: '',
    full_name: 'Pramod Yadav',
    avatar_url: null,
    role: 'member',
    department: 'Business Operations',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-6',
    org_id: 'org-1',
    email: '',
    full_name: 'Sanjeev Kumar',
    avatar_url: null,
    role: 'member',
    department: 'Business Operations',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-7',
    org_id: 'org-1',
    email: '',
    full_name: 'Disha Rajendra Katkhede',
    avatar_url: null,
    role: 'member',
    department: 'Finance Operations',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-8',
    org_id: 'org-1',
    email: '',
    full_name: 'Jayashree Bera',
    avatar_url: null,
    role: 'member',
    department: 'Sales',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-9',
    org_id: 'org-1',
    email: '',
    full_name: 'Ankit Shukla',
    avatar_url: null,
    role: 'member',
    department: 'Product & Analytics',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-10',
    org_id: 'org-1',
    email: '',
    full_name: 'Ayush Gautam',
    avatar_url: null,
    role: 'member',
    department: 'Category Management',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-11',
    org_id: 'org-1',
    email: '',
    full_name: 'Amrit Sampatram',
    avatar_url: null,
    role: 'member',
    department: 'Category Management',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-12',
    org_id: 'org-1',
    email: '',
    full_name: 'Rohit Kumar',
    avatar_url: null,
    role: 'member',
    department: 'Business Operations',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-13',
    org_id: 'org-1',
    email: '',
    full_name: 'Ritikh Mehta',
    avatar_url: null,
    role: 'member',
    department: 'Product & Analytics',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-14',
    org_id: 'org-1',
    email: '',
    full_name: 'Naman Narang',
    avatar_url: null,
    role: 'member',
    department: 'Product & Analytics',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-15',
    org_id: 'org-1',
    email: '',
    full_name: 'Yash',
    avatar_url: null,
    role: 'member',
    department: 'Product & Analytics',
    created_at: '2026-03-01T00:00:00Z',
  },
  {
    id: 'user-16',
    org_id: 'org-1',
    email: '',
    full_name: 'Ashish',
    avatar_url: null,
    role: 'member',
    department: 'Business Operations',
    created_at: '2026-03-30T00:00:00Z',
  },
];
